import sys
from src.logger import logging

def error_message_detail(error,error_detail:sys): # error - our custom error, error_details - details of error like line number, folder. This is generated by sys module.
    _,_,exc_tb=error_detail.exc_info() # first 2 info is not need , we need third info that conatils exception details.
    file_name=exc_tb.tb_frame.f_code.co_filename # extact file name.

    # creating message
    error_message="Error occured in python script name [{0}] line number [{1}] error message[{2}]".format(
     file_name,exc_tb.tb_lineno,str(error)) # getting file name and line number.

    return error_message

    
# custom exception class.
# Exception is the parent class which is inherited into class CustonException.
class CustomException(Exception): 
    def __init__(self,error_message,error_detail:sys): # constructer.
        super().__init__(error_message) # calling parent class.
        self.error_message=error_message_detail(error_message,error_detail=error_detail) # calling function
    
    def __str__(self): ## returning error.
        return self.error_message 
    
# if __name__ == "__main__":

#     try:
#         a = 10/0
#     except Exception as e:
#         logging.info("Zero division error")
#         raise CustomException(e, sys)  